### ISSUE TITLE
Skip beautiful soup?

### ISSUE THREAD

**Issue by bramtayl** [rufusrock/scraping_tools#2]
It looks like you're using beautiful soup in combination with the selenium html parser. I can see how beautifulsoup is a bit more convenient, but I think it would make the code simpler if you just used selenium css selectors?

**Comment by rufusrock** [comment]
Yeah - this one is mostly just me being lazy. BS does have easier methods for some things like traversing the HTML tree, finding_next element etc. Will work on this!
