### ISSUE TITLE
Simpler file names

### ISSUE THREAD

**Issue by bramtayl** [rufusrock/scraping_tools#7]
Instead of concatenating a bunch of info into csv file names, it would probably be easier to keep a separate table with that information, and just use the raw query as the csv filename

**Comment by rufusrock** [comment]
CSVs now save as just [query].csv 

Probably don't need to store date/time info elsewhere as it is included in each row of the csv and the file attribute?

**Comment by bramtayl** [comment]
Sure, but if the date/time of the search is the same/redundant in each row of the products csv, that's a sure sign it should be in a separate table instead
